GET http://localhost:3000/user 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NjczMjc3NTZ9.tsaQe_-FScK-uXvLSoQEFHzeevXEFWomsG48roQfzXU

###

POST http://localhost:3000/user/create
Content-Type: application/json

{
    "name": "Kevin", "password": "password"

}

###

POST http://localhost:3000/user/login 
Content-Type: application/json

{
    "name": "Kevin", "password": "password"

}

###
GET http://localhost:3000/progress 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NjczMjc3NTZ9.tsaQe_-FScK-uXvLSoQEFHzeevXEFWomsG48roQfzXU

###

POST http://localhost:3000/progress/update 
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NjczMjc3NTZ9.tsaQe_-FScK-uXvLSoQEFHzeevXEFWomsG48roQfzXU

{
    "language": "german", "category": "fruit"
}

###

GET http://localhost:3000/user/quiz/1/swedish
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NjczMjc3NTZ9.tsaQe_-FScK-uXvLSoQEFHzeevXEFWomsG48roQfzXU

###

GET http://localhost:3000/user/quiz/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NjczMjc3NTZ9.tsaQe_-FScK-uXvLSoQEFHzeevXEFWomsG48roQfzXU

###

POST http://localhost:3000/user/quiz
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NjczMjc3NTZ9.tsaQe_-FScK-uXvLSoQEFHzeevXEFWomsG48roQfzXU

{
    "name": "test name", 
    "language": "swedish", 
    "questions": 
    [
        {
        "question": "banana",
        "correctAnswer": "banan"
        },
        {
        "question": "apple",
        "correctAnswer": "äpple"
        }
    ]
}