GET http://localhost:3000/user 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NjY5NTgxMzUsImV4cCI6MTY2Njk1ODE0NX0.lw3Y95w7d924VRmBWyi4gH5bdRLB7FhgL_vx8KMOm8Q

###

POST http://localhost:3000/user/create
Content-Type: application/json

{
    "name": "Kevin", "password": "password"

}

###

POST http://localhost:3000/user/login 
Content-Type: application/json

{
    "name": "Kevin", "password": "password"

}

###
GET http://localhost:3000/progress 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NjY2ODg1Mjh9.m0EOH1j5p_Kui3aLyHaxpROuJ80zWpgupcFBsP7hY-M

###

POST http://localhost:3000/progress/update 
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NjY2ODg1Mjh9.m0EOH1j5p_Kui3aLyHaxpROuJ80zWpgupcFBsP7hY-M

{
    "language": "german", "category": "fruit"

}